name: 'Infer Android'
description: 'Run Infer on Gradle Project'

author: "Nick Jacob <nick.jacob@appmonet.com>"

branding:
  color: green
  icon: play

inputs:
  task:
    description: 'The ./gradlew command arguments'
    required: true
  github_token:
    description: 'Your github token'
    required: true

runs:
  using: 'docker'
  image: bknk/github-android-infer:v2
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
  args:
    - ${{ inputs.task }}
