name: 'Infer Android'
description: 'Run Infer on Gradle Project'

author: "Nick Jacob <nick.jacob@appmonet.com>"

branding:
  color: green
  icon: play

inputs:
  task:
    description: 'The ./gradlew command arguments'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  args:
    - ${{ inputs.task }}
